version: "3.8"

services:
    nodejs:
        build: 
            dockerfile: ./docker/node.dockerfile
            context: .
        image: r4deu51/
        container_name: \*/
        ports:
            - "3000"
        networks:
            - network
        environment:
            - NODE_ENV=production
    nginx:
        build: 
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: r4deu51/
        container_name: \*/
        ports:
            - "80:80"
            - "443:443"
        networks:
            - network

    redis:
        image: redis:alpine
        container_name: \*/
        networks:
            - network
        restart: always

    postgres:
        image: postgres:alpine
        container_name: asdsad
        networks:
            - network
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        restart: always

networks:
    network:
        driver: bridge