version: "3.8"

services:
    server:
        build: 
            dockerfile: ./docker/node.dockerfile
            context: .
        container_name: server_
        ports:
            - "3000:3000"
        networks:
            - network
        environment:
            - NODE_ENV=production
            - APP_ENV=production

networks:
    network:
        driver: bridge