version: "3.8"

services:
    nodejs:
        build: 
            dockerfile: ./docker/node-dev.dockerfile
            context: .
        image: r4deu51/
        container_name: \*/
        ports:
            - "3000"
        volumes:
            - ./:/app:rw
        networks:
            - network
    nginx:
        build: 
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: r4deu51/
        container_name: \*/
        ports:
            - "80:80"
            - "443:443"
        networks:
            - network
        depends_on:
            - nodejs
        restart: always

networks:
    network:
        driver: bridge