version: "3.8"

services:
    nodejs:
        build: 
            dockerfile: ./docker/node-dev.dockerfile
            context: .
        image: r4deu51/
        container_name: \*/
        ports:
            - "3000"
        volumes:
            - ./:/app:rw
        networks:
            - network
        environment:
            - NODE_ENV=development
    nginx:
        build: 
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: r4deu51/
        container_name: \*/
        ports:
            - "80:80"
            - "443:443"
        networks:
            - network
        depends_on:
            - nodejs
        restart: always

    mongo:
        image: mongo:alpine
        container_name: \*/
        networks:
            - network
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=mongo

    postgres:
        image: postgres:alpine
        container_name: asdsad
        networks:
            - network
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        restart: always

networks:
    network:
        driver: bridge    